/**
 * Self-hosts the two project typefaces so Be Me runs with no network at all.
 * Fetches only the latin subset of each weight and writes a @font-face sheet.
 *
 * Run:  node tools/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const OUT = 'public/fonts';

const FAMILIES = [
  { css: 'Chakra+Petch:wght@500;600;700', family: 'Chakra Petch', slug: 'chakra-petch' },
  { css: 'Inter:wght@400;500;600;700', family: 'Inter', slug: 'inter' },
];

await mkdir(OUT, { recursive: true });

const faces = [];

for (const spec of FAMILIES) {
  const css = await (
    await fetch(`https://fonts.googleapis.com/css2?family=${spec.css}&display=swap`, {
      headers: { 'User-Agent': UA },
    })
  ).text();

  // Keep only the latin subset blocks (the last ones Google emits per weight).
  const blocks = css.split('@font-face').slice(1);
  const latin = blocks.filter((b) => /unicode-range:\s*U\+0000-00FF/.test(b));

  for (const block of latin) {
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+\.woff2)\)/)?.[1];
    if (!weight || !url) continue;

    const file = `${spec.slug}-${weight}.woff2`;
    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
    await writeFile(`${OUT}/${file}`, bytes);
    console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} kB`);

    faces.push(
      `@font-face {\n` +
        `  font-family: '${spec.family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${file}') format('woff2');\n` +
        `}`,
    );
  }
}

await writeFile(
  `${OUT}/fonts.css`,
  `/* Generated by tools/fetch-fonts.mjs — self-hosted, no CDN at runtime. */\n\n${faces.join('\n\n')}\n`,
);
console.log(`wrote ${OUT}/fonts.css (${faces.length} faces)`);
