"""Core data structures shared by all three layers."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any

# Document classes drive how a file is parsed and how it is prioritized when
# packing a limited context window.
DOC_KINDS = ("standards", "pacing", "resource", "assessment", "unknown")


@dataclass
class Document:
    """One ingested source file."""

    doc_id: str
    path: str
    title: str
    kind: str = "unknown"
    text: str = ""
    pages: int = 0
    meta: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data.pop("text", None)  # kept out of the manifest; chunks carry the text
        return data


@dataclass
class Chunk:
    """A retrievable slice of a document."""

    chunk_id: str
    doc_id: str
    path: str
    kind: str
    ordinal: int
    text: str
    locator: str = ""            # human-readable citation target, e.g. "p. 4" / "row 12"
    grade: str = ""
    subject: str = ""
    codes: list[str] = field(default_factory=list)

    def citation(self) -> str:
        base = self.path
        return f"{base} ({self.locator})" if self.locator else base

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Chunk":
        return cls(**data)


@dataclass
class Standard:
    """A single standard / student expectation, verbatim from district sources.

    ``text`` is never generated by a model. It is copied from the corpus and
    re-injected into the finished lesson, which is what makes alignment
    verifiable rather than merely plausible.
    """

    code: str
    text: str
    grade: str = ""
    subject: str = ""
    strand: str = ""
    level: str = ""              # e.g. readiness / supporting / process
    source_path: str = ""
    locator: str = ""

    def citation(self) -> str:
        return f"{self.source_path} ({self.locator})" if self.locator else self.source_path

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Standard":
        return cls(**{k: v for k, v in data.items() if k in cls.__annotations__})


@dataclass
class PacingUnit:
    """One row of the scope and sequence."""

    unit_id: str
    grade: str
    subject: str
    unit_name: str
    sequence: int = 0
    weeks: str = ""
    start_date: str = ""
    end_date: str = ""
    days: int = 0
    standard_codes: list[str] = field(default_factory=list)
    focus: str = ""
    assessments: str = ""
    resources: str = ""
    source_path: str = ""
    locator: str = ""

    def label(self) -> str:
        prefix = f"Unit {self.sequence}: " if self.sequence else ""
        return f"{prefix}{self.unit_name}".strip()

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PacingUnit":
        return cls(**{k: v for k, v in data.items() if k in cls.__annotations__})


@dataclass
class LessonRequest:
    """What the teacher clicked in the UI."""

    grade: str
    subject: str
    unit: str = ""               # unit name or number; blank = let the mapper decide
    week: str = ""               # week label or date, used to pick the active unit
    lesson_number: int = 1
    duration_minutes: int = 60
    material: str = "lesson"     # "lesson" | "intervention"
    tier: str = "core"           # core | tier2 | tier3
    student_notes: str = ""      # e.g. "6 emergent bilingual students, 2 with IEPs"
    focus_standards: list[str] = field(default_factory=list)  # optional override

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class Violation:
    """A single failed validation rule."""

    rule: str
    severity: str                # "error" | "warning"
    message: str
    hint: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def __str__(self) -> str:  # pragma: no cover - display only
        return f"[{self.severity}] {self.rule}: {self.message}"


@dataclass
class ValidationReport:
    violations: list[Violation] = field(default_factory=list)
    checked: list[str] = field(default_factory=list)

    @property
    def errors(self) -> list[Violation]:
        return [v for v in self.violations if v.severity == "error"]

    @property
    def warnings(self) -> list[Violation]:
        return [v for v in self.violations if v.severity == "warning"]

    @property
    def ok(self) -> bool:
        return not self.errors

    def add(self, rule: str, severity: str, message: str, hint: str = "") -> None:
        self.violations.append(Violation(rule, severity, message, hint))

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "checked": self.checked,
            "errors": [v.to_dict() for v in self.errors],
            "warnings": [v.to_dict() for v in self.warnings],
        }


@dataclass
class GenerationResult:
    """Everything the pipeline produced, including how it got there."""

    request: LessonRequest
    unit: PacingUnit | None
    standards: list[Standard]
    document: dict[str, Any]                     # the lesson or intervention packet
    report: ValidationReport
    attempts: int = 1
    citations: list[str] = field(default_factory=list)
    context_report: dict[str, Any] = field(default_factory=dict)
    backend: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "request": self.request.to_dict(),
            "unit": self.unit.to_dict() if self.unit else None,
            "standards": [s.to_dict() for s in self.standards],
            "document": self.document,
            "validation": self.report.to_dict(),
            "attempts": self.attempts,
            "citations": self.citations,
            "context_report": self.context_report,
            "backend": self.backend,
        }
